name: AuditDNA Ultra UI Build

on:
  push:
    branches:
      - pr-7
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Package dist into zip
        run: |
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          ZIP_NAME="UI_Node${{ matrix.node-version }}_${TIMESTAMP}.zip"
          mkdir -p artifacts
          cd dist
          zip -r "../artifacts/$ZIP_NAME" .
          cd ..
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.node-version }}
          path: artifacts/*.zip

  # Optional: Deploy to Netlify (needs secrets)
  deploy:
    if: github.ref == 'refs/heads/pr-7'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install deps
        run: npm ci

      - name: Build for Netlify
        run: npm run build

      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
