name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.x

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Uncomment and edit the next step if you have a deployment script
      # - name: Deploy
      #   run: npm run deploy

      - name: Report build status
        run: |
          echo "Build and deployment workflow completed"