[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  
  # === AuditDNA App Variables ===
  VITE_API_BASE = "https://api.auditdna.org"
  VITE_ENV = "production"
  VITE_FEATURE_FLAGS = "usda,mortgage,factoring"
  VITE_OWNER_NAME = "AuditDNA"

# SPA redirects for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Asset caching for performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
