[build]
  command = ""
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command    = "npx http-server dist -p 5173 -c-1"
  port       = 3000
  targetPort = 5173
  publish    = "dist"
  functions  = "netlify/functions"
  autoLaunch = false