[build]
  command = ""
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command    = "node server.cjs"
  port       = 3000
  targetPort = 5173
  publish    = "dist"
  functions  = "netlify/functions"
  autoLaunch = false